logging:
  config: classpath:logback.xml

server:
  port: 8080

spring:
  application:
    name: byd-outsystem-simulate

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poi
    username: root
    password: root
  jpa:
    show-sql: true
    open-in-view: true
    database: MySQL

