server:
  port: 8181
spring:
  application:
    name: byd-outsystem-simulate
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/poi
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
logging:
  config: classpath:logback.xml
